[project]
name = "bioactivity"
version = "0.1.0"
description = "Systematic computational analysis of drug-metabolite pairs with corresponding bioactivity data"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chembl-structure-pipeline>=1.2.4",
    "chembl-webresource-client>=0.10.9",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "kaleido>=1.2.0",
    "matplotlib>=3.10.7",
    "nbformat>=5.10.4",
    "pip-system-certs>=5.3",
    "plotly>=6.5.0",
    "reaction-utils>=1.9.2",
    "rxnmapper>=0.4.2",
    "seaborn>=0.13.2",
    "setuptools<81",
]
